version: '3.9'

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    volumes:
      - ./services/backend:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  frontend:
    build:
      context: ./proyecto-votacion-front
      dockerfile: Dockerfile
    container_name: angularfrontend
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    ports:
      - "4200:80"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge

